language: c

install:
- sudo apt-get install build-essential

- wget https://github.com/zeromq/libzmq/releases/download/v4.2.3/zeromq-4.2.3.tar.gz
- tar -xzf zeromq-4.2.3.tar.gz
- cd zeromq-4.2.3

- ./autogen.sh
- ./configure
- make
- sudo make install
- sudo ldconfig

script:
- gcc zmq-pubsub-crash.c -L /usr/local/lib -lzmq
- ./a.out
