language: c

install:
# download libzmq-4.2.3
- wget https://github.com/zeromq/libzmq/releases/download/v4.2.3/zeromq-4.2.3.tar.gz
- tar -xzf zeromq-4.2.3.tar.gz

# compile libzmq
- pushd zeromq-4.2.3
- ./autogen.sh
- ./configure
- make
- sudo make install
- sudo ldconfig
- popd

# compile crash code
- gcc zmq-pubsub-crash.c -L /usr/local/lib -lzmq -std=c99 -o zmq-pubsub-crash

script:
- ulimit -c unlimited
- ./zmq-pubsub-crash
- gdb zmq-pubsub-crash core -ex bt -ex quit
